language: python

python:
    - "2.6"
    - "2.7"

install:
    - pip install -q coveralls --use-mirrors
    - pip install flake8

before_script:
    - flake8 origins

script:
    - coverage run test_strconv.py

after_success:
    - coveralls
